// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactPlastic$ReactTemplate = require("./reactPlastic.bs.js");

var $$default = ReasonReact.wrapReasonForJs(ReactPlastic$ReactTemplate.component, (function (jsProps) {
        return ReactPlastic$ReactTemplate.make(jsProps.children);
      }));

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* default Not a pure module */
