// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function getTypeString(optionType) {
  if (optionType !== undefined) {
    switch (optionType) {
      case 0 : 
          return "visa";
      case 1 : 
          return "amex";
      case 2 : 
          return "mastercard";
      case 3 : 
          return "discover";
      
    }
  } else {
    return "";
  }
}

function getCardType(cardNumber) {
  if (new RegExp("^4").test(cardNumber)) {
    return /* Visa */0;
  } else if (new RegExp("/^(5[1-5][0-9]{14}|2(22[1-9][0-9]{12}|2[3-9][0-9]{13}|[3-6][0-9]{14}|7[0-1][0-9]{13}|720[0-9]{12}))$/").test(cardNumber)) {
    return /* MasterCard */2;
  } else if (new RegExp("^3[47]").test(cardNumber)) {
    return /* Amex */1;
  } else if (new RegExp("^(6011|622(12[6-9]|1[3-9][0-9]|[2-8][0-9]{2}|9[0-1][0-9]|92[0-5]|64[4-9])|65)").test(cardNumber)) {
    return /* Discover */3;
  } else {
    return undefined;
  }
}

function getNumberOfCvcDigits(cardTypeOption) {
  if (cardTypeOption !== undefined && cardTypeOption !== 1) {
    return 3;
  } else {
    return 4;
  }
}

exports.getTypeString = getTypeString;
exports.getCardType = getCardType;
exports.getNumberOfCvcDigits = getNumberOfCvcDigits;
/* No side effect */
